on:
  deployment
jobs:
  event_info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This action does not do anything yet. It just prints out information that will be useful to get this working only on deployments that actually published a new episode"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.deployment.description: ${{ github.event.deployment.description }}"
          echo "github.event.deployment.ref: ${{ github.event.deployment.ref }}"
          echo "github.event.deployment.sha: ${{ github.event.deployment.sha }}"
          echo "github.event.deployment.task: ${{ github.event.deployment.task }}"
          echo "github.event.deployment.creator.login: ${{ github.event.deployment.creator.login }}"
#  publish_episode_to_twitter:
#    name: publish episode to twitter
#    runs-on: ubuntu-latest
#    steps:
#      - name: test a thing
#        run: echo "this is just a test for twitter"
#  publish_episode_to_linkedin:
#    name: publish episode to linkedin
#    runs-on: ubuntu-latest
#    steps:
#      - name: test a thing
#        run: echo "this is just a test for linkedin"
#  publish_episode_to_facebook:
#    name: publish episode to facebook
#    runs-on: ubuntu-latest
#    steps:
#      - name: test a thing
#        run: echo "this is just a test for facebook"
